/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-1",
    "aws_cognito_identity_pool_id": "us-west-1:b066540b-c59e-4e59-868d-8ec9524db567",
    "aws_cognito_region": "us-west-1",
    "aws_user_pools_id": "us-west-1_siRCXwvu1",
    "aws_user_pools_web_client_id": "62sruooqc3bogqvujj298tcr8o",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://k5u3i25v2vgl7i5ahffx553uj4.appsync-api.us-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-pifqd2lkjzg3nehfsvl6czv3j4",
    "aws_user_files_s3_bucket": "abucket53111-staging",
    "aws_user_files_s3_bucket_region": "us-west-1"
};


export default awsmobile;
